<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="right_leg" params="name parent *origin">

        <!-- J0 -->
        <joint name="${name}/j0_joint" type="revolute">
            <parent link="${parent}"/>
            <xacro:insert_block name="origin"/>
            <child link="${name}/j0_link"/>
            <axis xyz="0 0 -1"/>
            <limit lower="0" upper="${pi}" velocity="100" effort="100"/>
        </joint>

        <link name="${name}/j0_link">
            <visual>
                <origin xyz="0 0 -0.01"/>
                <geometry>
                    <box size="0.02 0.02 0.02"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 -0.01"/>
                <geometry>
                    <box size="0.02 0.02 0.02"/>
                </geometry>
            </collision>
            <xacro:inertial_box mass="0.1" x="0.02" y="0.02" z="0.02">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_box>
        </link>


        <!-- J1 -->
        <joint name="${name}/j1_joint" type="revolute">
            <parent link="${name}/j0_link"/>
            <child link="${name}/j1_link"/>
            <origin xyz="0 0 0" rpy="0 -${pi/2} 0"/>
            <axis xyz="0 -1 0"/>
            <limit lower="0" upper="${pi}" velocity="100" effort="100"/>
        </joint>
        
        <link name="${name}/j1_link">
            <visual>
                <origin xyz="${femur_length/2} 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <box size="${femur_length} 0.01 0.002"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="${femur_length/2} 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <box size="${femur_length} 0.01 0.002"/>
                </geometry>
            </collision>
            <xacro:inertial_box mass="0.1" x="${femur_length}" y="0.01" z="0.002">
                <origin xyz="${femur_length/2} 0 0" rpy="${pi/2} 0 0"/>
            </xacro:inertial_box>
        </link>


        <!-- J2 -->
        <joint name="${name}/j2_joint" type="revolute">
            <parent link="${name}/j1_link"/>
            <child link="${name}/j2_link"/>
            <origin xyz="${femur_length} 0 0" rpy="0 -${pi} 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="0" upper="${pi}" velocity="100" effort="100"/>
        </joint>
        
        <link name="${name}/j2_link">
            <visual>
                <origin xyz="${tibia_length/2} 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <box size="${tibia_length} 0.007 0.002"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="${tibia_length/2} 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <box size="${tibia_length} 0.007 0.002"/>
                </geometry>
            </collision>
            <xacro:inertial_box mass="0.1" x="${tibia_length}" y="0.007" z="0.002">
                <origin xyz="${tibia_length/2} 0 0" rpy="${pi/2} 0 0"/>
            </xacro:inertial_box>
        </link>

    </xacro:macro>
</robot>