<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- INCLUDES -->
    <xacro:include filename="inertial_macros.urdf.xacro"/>
    <xacro:include filename="materials.urdf.xacro"/>
    <xacro:include filename="left_leg.urdf.xacro"/>
    <xacro:include filename="right_leg.urdf.xacro"/>


    <!-- CONSTANTS -->
    <xacro:property name="body_length" value="0.16"/>
    <xacro:property name="body_width" value="0.10"/>
    <xacro:property name="body_height" value="0.003"/>

    <xacro:property name="femur_length" value="0.08"/>
    <xacro:property name="tibia_length" value="0.12"/>


    <!-- BASE LINK -->
    <link name="base_link">
    </link>

    <!-- BODY LINK -->
    <joint name="body_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body_link"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="body_link">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${body_length}" y="${body_width}" z="${body_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="body_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEGS -->
    <xacro:left_leg name="leg0" parent="body_link">
            <origin xyz="0 ${body_width/2} 0" rpy="0 0 0"/>
    </xacro:left_leg>

    <xacro:right_leg name="leg1" parent="body_link">
            <origin xyz="0 -${body_width/2} 0" rpy="0 0 ${pi}"/>
    </xacro:right_leg>


</robot>